config/routes.rb
Rails.application.routes.draw do
  resources :diaries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diary.rb
class Diary < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :set_diary, only: [:show, :edit, :update, :destroy]

  # GET /diaries
  # GET /diaries.json
  def index
    @diaries = Diary.all
  end

  # GET /diaries/1
  # GET /diaries/1.json
  def show
  end

  # GET /diaries/new
  def new
    @diary = Diary.new
  end

  # GET /diaries/1/edit
  def edit
  end

  # POST /diaries
  # POST /diaries.json
  def create
    @diary = Diary.new(diary_params)

    respond_to do |format|
      if @diary.save
        format.html { redirect_to @diary, notice: 'Diary was successfully created.' }
        format.json { render :show, status: :created, location: @diary }
      else
        format.html { render :new }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diaries/1
  # PATCH/PUT /diaries/1.json
  def update
    respond_to do |format|
      if @diary.update(diary_params)
        format.html { redirect_to @diary, notice: 'Diary was successfully updated.' }
        format.json { render :show, status: :ok, location: @diary }
      else
        format.html { render :edit }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diaries/1
  # DELETE /diaries/1.json
  def destroy
    @diary.destroy
    respond_to do |format|
      format.html { redirect_to diaries_url, notice: 'Diary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diary
      @diary = Diary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def diary_params
      params.require(:diary).permit(:name, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/views/diaries/_form.html.erb
<%= form_with(model: diary, local: true) do |form| %>
  <% if diary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(diary.errors.count, "error") %> prohibited this diary from being saved:</h2>

      <ul>
      <% diary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :名前 %>
    <%= form.text_field :name, id: :diary_name %>
  </div>

  <div class="field">
    <%= form.label :ひとこと %>
    <%= form.text_area :title, id: :diary_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/diaries/edit.html.erb
<div class="container">
<div class="page-header">
<h1>編集</h1>
</div>
<%= render 'form', diary: @diary %>

<%= link_to '見る', @diary,class: 'btn btn-primary' , :style=>"color:white;"%> 
<%= link_to '戻る', diaries_path,class: 'btn btn-primary' , :style=>"color:white;"%>
</div>

app/views/diaries/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container ">
<div class="page-header">
<h1>つぶやき</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>名前</th>
      <th>ひとこと</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @diaries.each do |diary| %>
      <tr>
        <td><%= diary.name %></td>
        <td><%= diary.title %></td>
        <td><%= link_to '見る', diary,class: 'btn btn-primary' , :style=>"color:white;"%></td>
        <td><%= link_to '編集', edit_diary_path(diary),class: 'btn btn-primary', :style=>"color:white;" %></td>
        <td><%= link_to '削除', diary, method: :delete, data: { confirm: 'Are you sure?' } ,class: 'btn btn-primary', :style=>"color:white;"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新規', new_diary_path,class: 'btn btn-primary' , :style=>"color:white;"%>
</div>

app/views/diaries/new.html.erb
<div class="container ">
<div class="page-header">
<h1>新規作成</h1>
</div>
<%= render 'form', diary: @diary %>

<%= link_to '戻る', diaries_path ,class: 'btn btn-primary', :style=>"color:white;"%>
</div>

app/views/diaries/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container ">
<p>
  <strong>名前</strong>
  <%= @diary.name %>
</p>

<p>
  <strong>ひとこと</strong>
  <%= @diary.title %>
</p>

<%= link_to '編集', edit_diary_path(@diary),class: 'btn btn-primary', :style=>"color:white;" %> 
<%= link_to '戻る', diaries_path,class: 'btn btn-primary', :style=>"color:white;" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>